plugins {
    id('com.gradleup.shadow') version '9.2.2'
}

repositories {
    maven { url = "https://repo.codemc.io/repository/nms/" }
    maven { url = "https://papermc.io/repo/repository/maven-public/" }
    maven { url = "https://hub.spigotmc.org/nexus/content/groups/public/" }
}

dependencies {
    implementation project(":api")
    implementation project(":flows")
    implementation project(":loader")

    compileOnly 'com.destroystokyo.paper:paper:1.16.5-R0.1-SNAPSHOT'
    compileOnly 'net.dmulloy2:ProtocolLib:5.4.0'
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

shadowJar {
    archiveBaseName.set('MultiLogin-Bukkit')

    if (System.getProperty("env", "AUTO") == "final") {
        archiveVersion.set(project.plugin_version as String)
    } else {
        String ver = "Build_" + version
        archiveVersion.set(ver)
    }
    archiveClassifier.set("")
    dependsOn(':core:shadowJar', ':bukkit:injector:shadowJar')

    from(project(':core').layout.buildDirectory.file('libs/MultiLogin-Core.JarFile'))
    from(project(':bukkit:injector').layout.buildDirectory.file('libs/MultiLogin-Bukkit-Injector.JarFile'))
}


artifacts {
    archives shadowJar
}
