plugins {
    id 'com.gradleup.shadow' version '9.1.0'
}

repositories {
    maven { url "https://repo.codemc.io/repository/maven-public/" }
    maven { url "https://papermc.io/repo/repository/maven-public/" }
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

dependencies {
    compileOnly project(":api")
    compileOnly project(":core")
    compileOnly project(":bungee")

    compileOnly group: 'net.md-5', name: 'bungeecord-proxy', version: '1.21-R0.1-SNAPSHOT'
}

shadowJar {
    archiveFileName = 'MultiLogin-Bungee-Injector.JarFile'
}

artifacts {
    archives shadowJar
}